### ISSUE TITLE
add src pytest config option to pyproject.toml

### ISSUE THREAD

**Issue by DonalChilde** [DonalChilde/cookiecutter-python-base#104]
add this to pyproject.toml so pytest can find things with a src layout.

```toml
[tool.pytest.ini_options]
pythonpath = "src"
```
